<<<<<<<< HEAD:migrations/versions/0be9da75eeb4_.py
"""empty message

Revision ID: 0be9da75eeb4
Revises: 
Create Date: 2025-01-02 09:28:26.828423
========
"""fresh migrate

Revision ID: d113d2db59ca
Revises: 
Create Date: 2024-12-31 14:00:58.726642
>>>>>>>> 1df0a7d (delete old migrations & reinitialized db with fresh migration - Files: migrations/README migrations/alembic.ini migrations/env.py migrations/versions/20201120_150602_create_users_table.py migrations/versions/20241219_164519_create_group_table.py migrations/versions/20241220_104742_create_badges_categories_events_.py migrations/versions/20241229_153324_remove_categories_badges_add_feedback.py migrations/versions/20241229_175259_create_rsvp.py migrations/versions/20241229_175944_.py migrations/versions/20241230_105039_.py migrations/versions/d113d2db59ca_fresh_migrate.py):migrations/versions/d113d2db59ca_fresh_migrate.py

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/0be9da75eeb4_.py
revision = '0be9da75eeb4'
========
revision = 'd113d2db59ca'
>>>>>>>> 1df0a7d (delete old migrations & reinitialized db with fresh migration - Files: migrations/README migrations/alembic.ini migrations/env.py migrations/versions/20201120_150602_create_users_table.py migrations/versions/20241219_164519_create_group_table.py migrations/versions/20241220_104742_create_badges_categories_events_.py migrations/versions/20241229_153324_remove_categories_badges_add_feedback.py migrations/versions/20241229_175259_create_rsvp.py migrations/versions/20241229_175944_.py migrations/versions/20241230_105039_.py migrations/versions/d113d2db59ca_fresh_migrate.py):migrations/versions/d113d2db59ca_fresh_migrate.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE organizers SET SCHEMA {SCHEMA};")

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('profile_pic', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('categories', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('event_date', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.String(length=255), nullable=False),
    sa.Column('end_time', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('badge_url', sa.String(length=255), nullable=False),
    sa.Column('preview', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE events SET SCHEMA {SCHEMA};")

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
<<<<<<<< HEAD:migrations/versions/0be9da75eeb4_.py

    if environment == "production":
        op.execute(f"ALTER TABLE feedback SET SCHEMA {SCHEMA};")

========
>>>>>>>> 1df0a7d (delete old migrations & reinitialized db with fresh migration - Files: migrations/README migrations/alembic.ini migrations/env.py migrations/versions/20201120_150602_create_users_table.py migrations/versions/20241219_164519_create_group_table.py migrations/versions/20241220_104742_create_badges_categories_events_.py migrations/versions/20241229_153324_remove_categories_badges_add_feedback.py migrations/versions/20241229_175259_create_rsvp.py migrations/versions/20241229_175944_.py migrations/versions/20241230_105039_.py migrations/versions/d113d2db59ca_fresh_migrate.py):migrations/versions/d113d2db59ca_fresh_migrate.py
    op.create_table('requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE requests SET SCHEMA {SCHEMA};")

    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
<<<<<<<< HEAD:migrations/versions/0be9da75eeb4_.py

    if environment == "production":
        op.execute(f"ALTER TABLE groups SET SCHEMA {SCHEMA};")


========
>>>>>>>> 1df0a7d (delete old migrations & reinitialized db with fresh migration - Files: migrations/README migrations/alembic.ini migrations/env.py migrations/versions/20201120_150602_create_users_table.py migrations/versions/20241219_164519_create_group_table.py migrations/versions/20241220_104742_create_badges_categories_events_.py migrations/versions/20241229_153324_remove_categories_badges_add_feedback.py migrations/versions/20241229_175259_create_rsvp.py migrations/versions/20241229_175944_.py migrations/versions/20241230_105039_.py migrations/versions/d113d2db59ca_fresh_migrate.py):migrations/versions/d113d2db59ca_fresh_migrate.py
    op.create_table('rsvps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
<<<<<<<< HEAD:migrations/versions/0be9da75eeb4_.py

    if environment == "production":
        op.execute(f"ALTER TABLE rsvps SET SCHEMA {SCHEMA};")


========
>>>>>>>> 1df0a7d (delete old migrations & reinitialized db with fresh migration - Files: migrations/README migrations/alembic.ini migrations/env.py migrations/versions/20201120_150602_create_users_table.py migrations/versions/20241219_164519_create_group_table.py migrations/versions/20241220_104742_create_badges_categories_events_.py migrations/versions/20241229_153324_remove_categories_badges_add_feedback.py migrations/versions/20241229_175259_create_rsvp.py migrations/versions/20241229_175944_.py migrations/versions/20241230_105039_.py migrations/versions/d113d2db59ca_fresh_migrate.py):migrations/versions/d113d2db59ca_fresh_migrate.py
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('going', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE invites SET SCHEMA {SCHEMA};")

    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
<<<<<<<< HEAD:migrations/versions/0be9da75eeb4_.py

    if environment == "production":
        op.execute(f"ALTER TABLE messages SET SCHEMA {SCHEMA};")
========
>>>>>>>> 1df0a7d (delete old migrations & reinitialized db with fresh migration - Files: migrations/README migrations/alembic.ini migrations/env.py migrations/versions/20201120_150602_create_users_table.py migrations/versions/20241219_164519_create_group_table.py migrations/versions/20241220_104742_create_badges_categories_events_.py migrations/versions/20241229_153324_remove_categories_badges_add_feedback.py migrations/versions/20241229_175259_create_rsvp.py migrations/versions/20241229_175944_.py migrations/versions/20241230_105039_.py migrations/versions/d113d2db59ca_fresh_migrate.py):migrations/versions/d113d2db59ca_fresh_migrate.py
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('invites')
    op.drop_table('rsvps')
    op.drop_table('groups')
    op.drop_table('requests')
    op.drop_table('feedback')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('organizers')
    # ### end Alembic commands ###
